# This file was generated by GoReleaser. DO NOT EDIT.
cask "qf" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "ee762be797a98ce0db41b779cc50abff85a196b3467557ab5e96c9c39d4aa8a5"
      url "https://github.com/qualflare/qualflare-cli/releases/download/v#{version}/qf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "518eed4d7772b5af541904c310f26677a6a1ed44e3bf01577bfc80044ffc7371"
      url "https://github.com/qualflare/qualflare-cli/releases/download/v#{version}/qf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "36e7ab4c9f666a793cefc311c927bffdbfdd0a0906fdebb2d3f2dc8ab1652bfa"
      url "https://github.com/qualflare/qualflare-cli/releases/download/v#{version}/qf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1d96596546dfb444031990365f503103809d91f5a375c3feb5870baa0655ed7"
      url "https://github.com/qualflare/qualflare-cli/releases/download/v#{version}/qf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qf"
  desc "CLI tool for collecting test results for Qualflare"
  homepage "https://github.com/qualflare/qualflare-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qf"]
    end
  end

  # No zap stanza required

end
