# This file was generated by GoReleaser. DO NOT EDIT.
cask "qf" do
  version "0.1.30"

  on_macos do
    on_intel do
      sha256 "e3febac94bf5fbf565f3eda231b7a3ed978ec50487e0ae0954ebf96d59dd4349"
      url "https://github.com/qualflare/qualflare-cli/releases/download/v#{version}/qf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6513729db8ffff8e14af7cf4aa31422ff132ab5a7c171337dbc24f1bd8419f5"
      url "https://github.com/qualflare/qualflare-cli/releases/download/v#{version}/qf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca65d77ed279495d8963b43cf18b8607b27973ab77dff96fb6cf6633c3b94ef8"
      url "https://github.com/qualflare/qualflare-cli/releases/download/v#{version}/qf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "72013685230ae48f0ebca0e129d57b7f55d67acdd8d40fa535ddc1ba51a70436"
      url "https://github.com/qualflare/qualflare-cli/releases/download/v#{version}/qf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qf"
  desc "CLI tool for collecting test results for Qualflare"
  homepage "https://github.com/qualflare/qualflare-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qf"]
    end
  end

  # No zap stanza required

end
