# This file was generated by GoReleaser. DO NOT EDIT.
cask "qf" do
  version "0.1.28"

  on_macos do
    on_intel do
      sha256 "6d26a0fdb405c187786a86cbc0d8b6d2a693d51742ef866e8a247399cf4effc1"
      url "https://github.com/qualflare/qualflare-cli/releases/download/v#{version}/qf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9281cc0eb8c6e10437c11232f5275821adf12c55d5d6971745408846cbf544b5"
      url "https://github.com/qualflare/qualflare-cli/releases/download/v#{version}/qf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e7fe31dfe1012490bb5b2c4811ced0f8fef8758efe85299ef62027d5a8452c83"
      url "https://github.com/qualflare/qualflare-cli/releases/download/v#{version}/qf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "25dd4c1c4ddbf572e002f0c64b7b1d5ab93c0f4c672298a20d4ef2157d16ca05"
      url "https://github.com/qualflare/qualflare-cli/releases/download/v#{version}/qf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qf"
  desc "CLI tool for collecting test results for Qualflare"
  homepage "https://github.com/qualflare/qualflare-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qf"]
    end
  end

  # No zap stanza required

end
