# This file was generated by GoReleaser. DO NOT EDIT.
cask "qualflare-maestro" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "7783e51e6fce94e68a0127cf09bff27c5db8fc16c10de5df8d5fa4e4ef995786"
      url "https://github.com/Qualflare/qualflare-maestro/releases/download/v#{version}/qualflare-maestro_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3cdbe1816600fa3c943db98bcd3944ad42d80d5f6fbde3999ee7d70009d85290"
      url "https://github.com/Qualflare/qualflare-maestro/releases/download/v#{version}/qualflare-maestro_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "de730b3c2d8d3b50a6ddf563576854e72029971718905e269a577327c9162bf6"
      url "https://github.com/Qualflare/qualflare-maestro/releases/download/v#{version}/qualflare-maestro_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "49ed1b5a54cfec36adec5fc2ea96b8582bf0dd029d1038fe98abc02b88525a80"
      url "https://github.com/Qualflare/qualflare-maestro/releases/download/v#{version}/qualflare-maestro_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qualflare-maestro"
  desc "Native Maestro reporter for Qualflare"
  homepage "https://qualflare.com/maestro-test-reporting/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qualflare-maestro"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qualflare-maestro"]
    end
  end

  # No zap stanza required
end
