# This file was generated by GoReleaser. DO NOT EDIT.
cask "qualflare-maestro" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "5716f7d14e765d7cc394c4573aeab197b3baef0e266fc10a125c054dfebd29c4"
      url "https://github.com/Qualflare/qualflare-maestro/releases/download/v#{version}/qualflare-maestro_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "93597566ae4ba7272ac544e102e6ab03f12f522ee9a6e3cd2155fb8d7b43b4e7"
      url "https://github.com/Qualflare/qualflare-maestro/releases/download/v#{version}/qualflare-maestro_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4f079616711cf1acd3975870c2d60039bea377b60c754ca58385be6654c687d8"
      url "https://github.com/Qualflare/qualflare-maestro/releases/download/v#{version}/qualflare-maestro_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "49d03989bff60c4a98f4b800a23f11c2c52c7d5afd7facfeda35eaa477747032"
      url "https://github.com/Qualflare/qualflare-maestro/releases/download/v#{version}/qualflare-maestro_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qualflare-maestro"
  desc "Native Maestro reporter for Qualflare"
  homepage "https://qualflare.com/maestro-test-reporting/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qualflare-maestro"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qualflare-maestro"]
    end
  end

  # No zap stanza required
end
