# This file was generated by GoReleaser. DO NOT EDIT.
cask "qualflare-go" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "cfb73222214a7a586863b89023f4b5648cc2ea2fb4f0b5c8eefb9cf058543822"
      url "https://github.com/Qualflare/qualflare-go/releases/download/v#{version}/qualflare-go_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d535b41e2d770883cc4842d94a7551ee08762cd409893bd350e73709e9a3f12"
      url "https://github.com/Qualflare/qualflare-go/releases/download/v#{version}/qualflare-go_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "59759af0526769bc4bb68a252e8fcb56613f33fc81ee3935876529fb54dcd5b3"
      url "https://github.com/Qualflare/qualflare-go/releases/download/v#{version}/qualflare-go_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b7686a8d2d8fe7d573c3dac124e5383a2ef1ccea2557e02187b6704ef0395b0"
      url "https://github.com/Qualflare/qualflare-go/releases/download/v#{version}/qualflare-go_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qualflare-go"
  desc "Native go test reporter for Qualflare"
  homepage "https://qualflare.com/go-test-reporting/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qualflare-go"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qualflare-go"]
    end
  end

  # No zap stanza required
end
