# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qf < Formula
  desc "CLI tool for collecting test results for Qualflare"
  homepage "https://github.com/qualflare/qualflare-cli"
  version "0.1.10-rc.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qualflare/qualflare-cli/releases/download/v0.1.10-rc.1/qf_0.1.10-rc.1_darwin_amd64.tar.gz"
      sha256 "52f02dcda77f64ac5b61597ecc5b402eeaa59a26caab727364760cbbb8df1cf7"

      define_method(:install) do
        bin.install "qf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qualflare/qualflare-cli/releases/download/v0.1.10-rc.1/qf_0.1.10-rc.1_darwin_arm64.tar.gz"
      sha256 "a4167ba9a170d9bbb8f5e4e0dec2b981cd0680a1affddc5815f1c31f47d1aed5"

      define_method(:install) do
        bin.install "qf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qualflare/qualflare-cli/releases/download/v0.1.10-rc.1/qf_0.1.10-rc.1_linux_amd64.tar.gz"
      sha256 "0e793067dd61ced9e9e99d7f8debab61bc201315b917e0fd85e1bea16b4a72fd"
      define_method(:install) do
        bin.install "qf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qualflare/qualflare-cli/releases/download/v0.1.10-rc.1/qf_0.1.10-rc.1_linux_arm64.tar.gz"
      sha256 "cea04e51eb6ca00210089931033f58f8045045707a8caed4286af6dc4608a4d6"
      define_method(:install) do
        bin.install "qf"
      end
    end
  end

  test do
    system "#{bin}/qf", "version"
  end
end
