# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QualflareGo < Formula
  desc "Native go test reporter for Qualflare"
  homepage "https://github.com/Qualflare/qualflare-go"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Qualflare/qualflare-go/releases/download/v0.1.1/qualflare-go_0.1.1_darwin_amd64.tar.gz"
      sha256 "07bcffb4cc445fbcbcf3c8899951e9adb376c44addd2c35630138b678314eb94"

      define_method(:install) do
        bin.install "qualflare-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Qualflare/qualflare-go/releases/download/v0.1.1/qualflare-go_0.1.1_darwin_arm64.tar.gz"
      sha256 "da2c65cfe628a26df662d311cb44a995a709597055111edcf8963f6956de953b"

      define_method(:install) do
        bin.install "qualflare-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qualflare/qualflare-go/releases/download/v0.1.1/qualflare-go_0.1.1_linux_amd64.tar.gz"
      sha256 "7d7d21b5d8e928c6e6595a8c48cfa0202692b76623ecff2ebfebc368ef15a40f"
      define_method(:install) do
        bin.install "qualflare-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qualflare/qualflare-go/releases/download/v0.1.1/qualflare-go_0.1.1_linux_arm64.tar.gz"
      sha256 "4b5348ea60ea776edfd98f2d6081e2e3e65ab87c69a6d0c444458a6c48c6c477"
      define_method(:install) do
        bin.install "qualflare-go"
      end
    end
  end

  test do
    system "#{bin}/qualflare-go", "-version"
  end
end
